# Generated by Django 4.2.16 on 2024-09-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_sectionimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionURLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('alt_text', models.CharField(max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_urls', to='projects.section')),
            ],
            options={
                'ordering': ['section_id', 'display_order'],
            },
        ),
    ]
