# Generated by Django 4.2.16 on 2024-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_sectionurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
