# Generated by Django 4.2.16 on 2024-09-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_sub_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
