# Generated by Django 4.2.16 on 2024-09-18 13:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_image_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
