# Generated by Django 4.2.16 on 2024-09-19 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_detail_image_project_detail_image_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionurls',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='sectionurls',
            old_name='alt_text',
            new_name='link_text',
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='https://www.google.com/', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='link_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
