# Generated by Django 4.2.16 on 2024-09-19 08:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_url_sectionurls_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimages',
            name='video',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='sectionimages',
            name='video_alt_text',
            field=models.CharField(default='placeholder', max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='heading_1',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='heading_2',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sectionimages',
            name='alt_text',
            field=models.CharField(default='placeholder', max_length=200),
        ),
    ]
