# Generated by Django 4.2.16 on 2024-09-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_sectionimages_video_sectionimages_video_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='heading_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='heading_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
