# Generated by Django 4.2.16 on 2024-09-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_skill_options'),
        ('projects', '0010_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='consultant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_access', to='home.consultant'),
        ),
    ]
