# Generated by Django 4.2.16 on 2024-09-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_client_user_id_client_allow_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='allow_delete',
            field=models.BooleanField(),
        ),
    ]
