# Generated by Django 4.2.16 on 2024-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_in_home',
            field=models.BooleanField(default=True),
        ),
    ]
