# Generated by Django 4.2.16 on 2024-09-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_show_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimages',
            name='image_caption_heading',
            field=models.CharField(default='Caption Heading', max_length=250),
        ),
        migrations.AddField(
            model_name='sectionimages',
            name='image_caption_text',
            field=models.CharField(default='Caption Text', max_length=250),
        ),
    ]
