# Generated by Django 4.2.16 on 2024-09-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_sectionimages_image_caption_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimages',
            name='image_caption_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
