# Generated by Django 4.2.16 on 2024-09-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_sectionimages_image_caption_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionimages',
            name='image_caption_color',
        ),
    ]
