# Generated by Django 4.2.16 on 2024-09-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_sectionimages_image_caption_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimages',
            name='image_caption_mode',
            field=models.CharField(default='light', max_length=100),
        ),
    ]
