# Generated by Django 4.2.16 on 2024-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_sectionimages_image_caption_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionimages',
            name='image_caption_heading',
            field=models.CharField(blank=True, default='Caption Heading', max_length=250),
        ),
        migrations.AlterField(
            model_name='sectionimages',
            name='image_caption_mode',
            field=models.CharField(blank=True, default='light', max_length=100),
        ),
        migrations.AlterField(
            model_name='sectionimages',
            name='image_caption_text',
            field=models.CharField(blank=True, default='Caption Text', max_length=250),
        ),
    ]
