# Generated by Django 4.2.16 on 2024-09-26 12:37

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_sectionimages_image_caption_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionimages',
            name='video',
        ),
        migrations.RemoveField(
            model_name='sectionimages',
            name='video_alt_text',
        ),
        migrations.CreateModel(
            name='SectionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='video')),
                ('video_alt_text', models.CharField(default='placeholder', max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_videos', to='projects.section')),
            ],
            options={
                'ordering': ['section_id', 'display_order'],
            },
        ),
    ]
