# Generated by Django 4.2.16 on 2024-10-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_sectionimages_video_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionURLS',
            new_name='SectionURL',
        ),
    ]
