# Generated by Django 4.2.16 on 2024-10-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_rename_sectionurls_sectionurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionImages',
            new_name='SectionImage',
        ),
    ]
