# Generated by Django 4.2.16 on 2024-09-19 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('cr_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True)),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-request_date', 'last_name', 'first_name'],
            },
        ),
    ]
