# Generated by Django 4.2.16 on 2024-09-19 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
