# Generated by Django 4.2.16 on 2024-09-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_collaborationrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationrequest',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='message',
            field=models.TextField(),
        ),
    ]
