# Generated by Django 4.2.16 on 2024-09-30 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_how'),
        ('contact', '0005_alter_collaborationrequest_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborationrequest',
            options={'ordering': ['consultant_id', '-request_date', 'last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='consultant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_collaboration', to='home.consultant'),
        ),
    ]
