# Generated by Django 4.2.16 on 2024-09-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_consultant_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
