# Generated by Django 4.2.16 on 2024-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_skill_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastemployment',
            options={'ordering': ['consultant_id', '-start']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['consultant_id', 'type']},
        ),
        migrations.AlterField(
            model_name='pastemployment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
