# Generated by Django 4.2.16 on 2024-09-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_pastemployment_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
