# Generated by Django 4.2.16 on 2024-09-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_skill_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['consultant_id', 'type', 'display_order']},
        ),
    ]
