# Generated by Django 4.2.16 on 2024-09-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_skill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='consultant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_config', to='home.consultant'),
            preserve_default=False,
        ),
    ]
