# Generated by Django 4.2.16 on 2024-09-25 10:01

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_config_consultant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['key']},
        ),
        migrations.AddField(
            model_name='consultant',
            name='intro_text_heading',
            field=models.CharField(default='heading.', max_length=200),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=250)),
                ('link', models.URLField(max_length=250)),
                ('logo', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('logo_alt_text', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_customers', to='home.consultant')),
            ],
            options={
                'ordering': ['consultant_id', 'name'],
            },
        ),
    ]
