# Generated by Django 4.2.16 on 2024-09-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_config_options_consultant_intro_text_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(max_length=250)),
                ('link', models.URLField(max_length=250)),
                ('fa_icon', models.CharField(blank=True, max_length=200)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_socialaccounts', to='home.consultant')),
            ],
        ),
    ]
