# Generated by Django 4.2.16 on 2024-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_socialaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
