# Generated by Django 4.2.16 on 2024-09-25 13:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_socialaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastemployment',
            name='link',
            field=models.URLField(default='https://www.google.com', max_length=250),
        ),
        migrations.AddField(
            model_name='pastemployment',
            name='link_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pastemployment',
            name='logo',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='pastemployment',
            name='logo_alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
