# Generated by Django 4.2.16 on 2024-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_pastemployment_link_pastemployment_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='about_me',
            field=models.TextField(default='default about me text.'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
