# Generated by Django 4.2.16 on 2024-09-26 21:53

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_consultant_about_me_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='How',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='heading.', max_length=200)),
                ('text', models.TextField(default='default intro text.')),
                ('icon', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('display_order', models.IntegerField(default=0)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_hows', to='home.consultant')),
            ],
        ),
    ]
