# Generated by Django 4.2.16 on 2024-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_how'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastemployment',
            name='link',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
